name: CI

on:
  push:
    branches:
      - master
      - dev/*
      - feature/*
      - hotfix/*
      - release/*

jobs:
  build-api:
    name: Building Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Prepare prerelease semantic
        if: github.ref != 'refs/heads/master'
        run: |
          mv .releaserc.prerelease.yaml .releaserc.yaml

      - name: Using .releaserc.yaml
        run: |
          cat .releaserc.yaml

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          semantic_version: 17
          extra_plugins: |
            @semantic-release/changelog@5
            @semantic-release/exec@5
            @semantic-release/git@9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         # S3_BUCKET: ${{ secrets.S3_BUCKET }}
